### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas-checks#81]
Atlas checks is throwing a `ConcurrentModificationException` based around the `EventService` class. This is a run time exception that is breaking execution of the program

```
2018-10-19 10:16:55 ERROR Command:285 - Command execution failed.
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
        at java.lang.Iterable.forEach(Iterable.java:74)
        at org.openstreetmap.atlas.checks.event.EventService.complete(EventService.java:65)
        at org.openstreetmap.atlas.checks.distributed.IntegrityCheckSparkJob.lambda$start$1401df6c$1(IntegrityCheckSparkJob.java:372)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1018)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1018)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$32.apply(RDD.scala:912)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$32.apply(RDD.scala:912)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1869)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1869)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

This appears to be caused by the updates in https://github.com/osmlab/atlas-checks/pull/74. Line 65 iterating through `processors` and removing from `processors` by calling `unregister()`.

**Comment by Bentleysb** [comment]
This is all good now. Thanks @jklamer!
